import Link from "next/link"
import Head from 'next/head'

export default function Home() {
  return (
    <div className='container px-4 pt-5'>
      <Head>
        <title>Learn Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Bienvenue sur Code.io</h1>
     <span>Le blog communautaire de développement web</span> 

      <div className="row mt-5">

        <div className="clo-12 col-sm-6">
          <div className="card w-100 h-100">
            <div className="card-body">
            <h5 className="card-title">Lisez les articles</h5>
            <h6 className="card-subtitle mb-2 text-muted">Maximisez votre culture web</h6>
            <p className="card-text">Chaque auteur tente de vous apporter leur aide</p>
            <Link href='/blog'>Visiter le blog</Link>
            </div>
          </div>
        </div>

        <div className="clo-12 col-sm-6" style={{minHeight: '200px'}}>
          <div className="card w-100 h-100">
            <div className="card-body">
            <h5 className="card-title">Lisez les articles</h5>
            <h6 className="card-subtitle mb-2 text-muted">rencontrez des devs</h6>
            <p className="card-text">Ajoutez, invitez et discutez avec les différents membres.</p>
            <Link href='/blog'>découvrez la liste de membres</Link>
            </div>
          </div>
        </div>
    
      </div>
    </div>
  )
}
